version: '3'


networks:
  nginx-php81-mysql8-node:

services:

   # nginx
  nginx-service:
      image: nginx:stable-alpine
      container_name: nginx-container
      ports:
        - "80:80"
      volumes:
        - ./app:/var/www/project
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php74-service
        - mysql8-service
      networks:
        - nginx-php81-mysql8-node

   # php
  php74-service:
      build:
        context: .
      container_name: php74-container
      ports:
        - "9000:9000"
      volumes:
        - ./app:/var/www/project
      networks:
        - nginx-php81-mysql8-node

   #myslq
  mysql8-service:
      image: mysql:8
      container_name: myslq8-container
      ports:
        - "3306:3306"
      volumes:
        - ./mysql:/var/lib/mysql
        - ./init.sql:/data/application/init.sql
      command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_PASSWORD: secret
      networks:
        - nginx-php81-mysql8-node
