<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '7e8fa179ab98f6acd8263cbc8ea3704a',
  'DATABASE_URL' => 'mysql://root:secret@mysql8-service:3306/app?serverVersion=8&charset=utf8mb4',
  'AWS_S3_ACCESS_ID' => 'AKIAZ42R5E333FT4KF7K',
  'AWS_S3_ACCESS_SECRET' => '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',
  'AWS_S3_ACCESS_BUCKET' => 'new-bucket-27-11-2022',
);
